"""What happens when an agent is installed into a tier.

Two steps, in order:

1. Copy the agent directory down from the user master into the target
   tier. The semantics are LifeOS's ``copyMissing`` narrowed to a single
   named agent: copy when absent, never overwrite when present. An agent
   already installed at the destination may have been edited on purpose —
   clobbering it would silently discard local work — so the only way to
   refresh a copy is to remove it first.
2. Generate the per-harness pointer files that make the copied agent
   discoverable, per the formats specified in
   ``harness-adapters/<harness>/README.md``.

A pointer is a pointer: it carries the agent's name, description, and the
lists of its Skills and Workflows, then points at ``AGENT.md`` for
everything else. Agent content is never duplicated into a generated file,
so there is exactly one copy of an agent's instructions per tier and no
way for a pointer to go stale against the thing it points at.
"""

from __future__ import annotations

import shutil
from pathlib import Path

from . import catalog, tiers

__all__ = [
    "copy_agent",
    "generate_harness_adapters",
    "detect_harnesses",
    "harness_pointer_path",
    "tier_name_for",
    "HARNESSES",
]

#: Every harness this repo knows how to write a pointer for, in the order
#: results are reported. Adding one means a new ``harness-adapters/<name>/``
#: directory specifying its format, plus an entry in each dispatch below.
HARNESSES = ("claude-code", "cline", "gemini-cli", "qwen-code")

#: Present in every file and block this module writes. Its absence in an
#: existing file is what marks that file as hand-authored — see
#: ``_write_pointer_file``.
GENERATED_MARKER = "Generated by ai-agents"

#: Exact managed-block markers for the context-file harnesses. These are
#: matched literally against files humans also edit, so they are spelled
#: once here and never rebuilt from parts.
BLOCK_BEGIN = "<!-- BEGIN ai-agents (generated — do not edit inside this block) -->"
BLOCK_END = "<!-- END ai-agents -->"


def copy_agent(name: str, src_root: Path, dst_root: Path) -> bool:
    """Copy ``src_root/agents/<name>`` to ``dst_root/agents/<name>``.

    Returns ``True`` if the agent was copied, ``False`` if it was already
    present at the destination and was therefore left untouched. Raises
    ``FileNotFoundError`` if the agent does not exist in the source tier.

    ``dirs_exist_ok=False`` is kept as a second line of defense behind the
    existence check — if the check is ever wrong, the copy fails loudly
    instead of merging two trees.
    """
    src = Path(src_root) / "agents" / name
    dst = Path(dst_root) / "agents" / name

    if not src.is_dir():
        raise FileNotFoundError(f"agent {name!r} not found in {src_root}")

    if dst.exists():
        return False

    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copytree(src, dst, dirs_exist_ok=False)
    return True


# --------------------------------------------------------------------------
# Where a tier's pointers land
# --------------------------------------------------------------------------


def tier_name_for(tier_root: Path) -> str:
    """Name the tier (``"project"``/``"workspace"``/``"user"``) at ``tier_root``.

    Generation needs the tier's *name* — it goes into every pointer as
    ``Tier:`` — but callers naturally hold its *path*. The CLI knows which
    tier it was asked for and passes it explicitly; this is the fallback for
    direct API calls, and it works by asking ``tiers.resolve`` what it would
    call this path.

    Raises ``ValueError`` when ``tier_root`` is not a tier root at all,
    rather than guessing: the answer gets written into generated files, and
    a wrong guess there is a lie that persists on disk.
    """
    tier_root = Path(tier_root).expanduser().resolve()

    if tier_root == tiers.user_root().expanduser().resolve():
        return "user"

    resolved = tiers.resolve(tier_root.parent)
    for name in ("project", "workspace"):
        candidate = resolved[name]
        if candidate is not None and candidate.expanduser().resolve() == tier_root:
            return name

    raise ValueError(
        f"{tier_root} is not a recognized tier root; pass tier= explicitly"
    )


def _harness_root(tier_root: Path, tier: str) -> Path:
    """The directory a harness reads its configuration from, for this tier.

    For the project and workspace tiers that is the directory *containing*
    ``.ai-agents/`` — the repo root or the workspace folder — because that
    is where the harness is launched. For the user tier it is the home
    directory, where every harness keeps its global configuration.
    """
    return Path.home() if tier == "user" else Path(tier_root).parent


def harness_pointer_path(harness: str, tier_root: Path, tier: str, agent_name: str) -> Path:
    """Where ``harness``'s pointer for ``agent_name`` lives at this tier.

    Per-agent-file harnesses get a path ending in ``<agent_name>.md``;
    context-file harnesses get the shared file their managed block lives in,
    and ignore ``agent_name`` entirely.
    """
    root = _harness_root(tier_root, tier)

    if harness == "claude-code":
        return root / ".claude" / "agents" / f"{agent_name}.md"
    if harness == "cline":
        return root / ".clinerules" / f"{agent_name}.md"
    if harness == "gemini-cli":
        return (root / ".gemini" / "GEMINI.md") if tier == "user" else (root / "GEMINI.md")
    if harness == "qwen-code":
        return (root / ".qwen" / "QWEN.md") if tier == "user" else (root / "QWEN.md")

    raise ValueError(f"unknown harness {harness!r}")


def detect_harnesses(tier_root: Path, tier: str) -> list[str]:
    """Which harnesses are in use at this tier, in ``HARNESSES`` order.

    Detection is deliberately a read-only test for configuration a harness
    has *already* created — a `.claude/` directory, a `GEMINI.md`, and so on
    — and never creates anything itself. Installing an agent should make it
    visible to the tools someone actually uses; it should not litter a repo
    with config directories for three tools they don't.

    Kept separate from generation so it can be tested on its own and so
    ``doctor`` (issue #15) can reuse it to report what it found.
    """
    root = _harness_root(tier_root, tier)
    found = []

    if (root / ".claude").is_dir():
        found.append("claude-code")
    if (root / ".clinerules").is_dir():
        found.append("cline")
    # The context-file harnesses are detected by either their config
    # directory or a context file already sitting at the root, since a
    # project can have a hand-written GEMINI.md and no .gemini/ at all.
    if (root / ".gemini").is_dir() or harness_pointer_path("gemini-cli", tier_root, tier, "_").is_file():
        found.append("gemini-cli")
    if (root / ".qwen").is_dir() or harness_pointer_path("qwen-code", tier_root, tier, "_").is_file():
        found.append("qwen-code")

    return found


# --------------------------------------------------------------------------
# Rendering
# --------------------------------------------------------------------------


def _kind_lines(agent: dict, bullet: str = "") -> list[str]:
    """Render an agent's Skills and Workflows lines.

    Each kind gets its own line and an empty kind is dropped entirely rather
    than printed with nothing after the colon; only an agent with neither
    kind falls back to a single ``(none)``. This is the same convention
    ``cli.list_cmd`` uses — every ``harness-adapters/*/README.md`` says so
    explicitly — so the two should change together.
    """
    skills = agent.get("skills") or []
    workflows = agent.get("workflows") or []

    if not skills and not workflows:
        return [f"{bullet}(none)"]

    lines = []
    if skills:
        lines.append(f"{bullet}Skills: {', '.join(skills)}")
    if workflows:
        lines.append(f"{bullet}Workflows: {', '.join(workflows)}")
    return lines


def _render_claude_code(agent: dict, agent_path: Path, tier: str) -> str:
    kinds = "\n".join(_kind_lines(agent))
    return (
        "---\n"
        f"name: {agent['name']}\n"
        f"description: {agent['description']}\n"
        "---\n"
        "\n"
        f"<!-- {GENERATED_MARKER}. Do not hand-edit this file — edit\n"
        f"     {agent_path} instead and reinstall. -->\n"
        "\n"
        f"{kinds}\n"
        "\n"
        "Full instructions and boundaries for this agent are at:\n"
        "\n"
        f"{agent_path}\n"
        "\n"
        f"Resolved tier: {tier}.\n"
    )


def _render_cline(agent: dict, agent_path: Path, tier: str) -> str:
    kinds = "\n".join(_kind_lines(agent))
    # Cline loads every .clinerules file on every request, so an empty
    # description is dropped rather than left as a blank paragraph.
    description = f"{agent['description']}\n\n" if agent["description"] else ""
    return (
        f"<!-- {GENERATED_MARKER}. Do not hand-edit — edit {agent_path}\n"
        "     and reinstall. -->\n"
        "\n"
        f"# {agent['name']}\n"
        "\n"
        f"{description}"
        f"{kinds}\n"
        f"Full instructions: {agent_path}\n"
        f"Tier: {tier}\n"
    )


def _render_context_block(agents: list[dict], tier_root: Path, tier: str) -> str:
    """The managed block shared by the Gemini CLI and Qwen Code adapters.

    One ``### <name>`` entry per agent installed at this tier, alphabetical
    (``catalog.list_agents`` already sorts by name), so the block is
    byte-identical between runs and diffs cleanly.
    """
    entries = []
    for agent in agents:
        agent_path = _agent_md_path(tier_root, agent)
        kinds = "\n".join(_kind_lines(agent, bullet="- "))
        description = f"{agent['description']}\n\n" if agent["description"] else ""
        entries.append(
            f"### {agent['name']}\n"
            "\n"
            f"{description}"
            f"{kinds}\n"
            f"- Full instructions: {agent_path}\n"
            f"- Tier: {tier}\n"
        )

    body = "\n".join(entries)
    return (
        f"{BLOCK_BEGIN}\n"
        f"<!-- {GENERATED_MARKER}. Do not hand-edit this block — edit the\n"
        "     source AGENT.md files and reinstall; this block is fully\n"
        "     regenerated each time. -->\n"
        "\n"
        "## AI Agents\n"
        "\n"
        f"{body}"
        "\n"
        f"{BLOCK_END}\n"
    )


def _agent_md_path(tier_root: Path, agent: dict) -> Path:
    """Absolute path to the ``AGENT.md`` a pointer points at."""
    return (Path(agent["path"]) / "AGENT.md").resolve()


# --------------------------------------------------------------------------
# Writing
# --------------------------------------------------------------------------


def _write_pointer_file(path: Path, content: str) -> dict:
    """Write a whole-file pointer, refusing to clobber a hand-authored file.

    Three outcomes. Identical content is not rewritten at all, which is what
    makes repeated installs idempotent down to the file mtime. A file
    carrying ``GENERATED_MARKER`` is ours and is regenerated. A file without
    it was written by a person — Claude Code and Cline both use directories
    users put their own files in — so it is left exactly as it is and
    reported back to the caller instead.
    """
    existed = path.exists()

    if existed:
        current = path.read_text(encoding="utf-8")
        if current == content:
            return {"action": "unchanged", "reason": None}
        if GENERATED_MARKER not in current:
            return {"action": "skipped", "reason": "file was not generated by ai-agents"}

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return {"action": "updated" if existed else "created", "reason": None}


def _write_managed_block(path: Path, block: str) -> dict:
    """Replace the managed block in a shared context file, and nothing else.

    ``GEMINI.md`` and ``QWEN.md`` belong to the user; this only ever rewrites
    the span between the markers. A missing file is created holding just the
    block, a file without markers gets the block appended, and a file with a
    ``BEGIN`` but no ``END`` after it is malformed — that one is reported
    rather than repaired, because every way of guessing where the block was
    meant to stop risks eating text a person wrote.
    """
    if not path.exists():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(block, encoding="utf-8")
        return {"action": "created", "reason": None}

    current = path.read_text(encoding="utf-8")
    begin = current.find(BLOCK_BEGIN)

    if begin == -1:
        separator = "" if current.endswith("\n\n") else ("\n" if current.endswith("\n") else "\n\n")
        updated = f"{current}{separator}{block}"
    else:
        end = current.find(BLOCK_END, begin)
        if end == -1:
            return {"action": "skipped", "reason": f"unterminated ai-agents block in {path.name}"}
        after = current[end + len(BLOCK_END) :]
        # The block renders with a trailing newline of its own; drop the one
        # immediately following END so re-running cannot accumulate blanks.
        after = after[1:] if after.startswith("\n") else after
        updated = f"{current[:begin]}{block}{after}"

    if updated == current:
        return {"action": "unchanged", "reason": None}

    path.write_text(updated, encoding="utf-8")
    return {"action": "updated", "reason": None}


# --------------------------------------------------------------------------
# Entry point
# --------------------------------------------------------------------------


def generate_harness_adapters(
    agent_name: str,
    tier_root: Path,
    *,
    tier: str | None = None,
) -> list[dict]:
    """Write pointer files for every harness detected at ``tier_root``.

    ``agent_name`` is the agent's directory name under ``tier_root/agents/``
    — the same name ``install`` was given. It selects the file to write for
    the per-agent harnesses (Claude Code, Cline). The context-file harnesses
    (Gemini CLI, Qwen Code) keep one combined block listing every agent
    installed at the tier, so those are regenerated in full on every call
    regardless of which agent triggered it; that is what keeps the block
    correct after any install.

    ``tier`` is inferred from ``tier_root`` when omitted — see
    ``tier_name_for``.

    Returns one ``{"harness", "path", "action", "reason"}`` dict per detected
    harness, in ``HARNESSES`` order, where ``action`` is ``created``,
    ``updated``, ``unchanged``, or ``skipped``. An empty list means no
    supported harness was detected, which is not an error — it is the normal
    state of a repo that uses none of them.

    Raises ``FileNotFoundError`` if ``agent_name`` is not installed at
    ``tier_root``.
    """
    tier_root = Path(tier_root)
    tier = tier if tier is not None else tier_name_for(tier_root)

    agent = catalog.read_agent(tier_root / "agents" / agent_name)
    if agent is None:
        raise FileNotFoundError(f"agent {agent_name!r} is not installed at {tier_root}")

    results = []
    for harness in detect_harnesses(tier_root, tier):
        # Pointer filenames use the on-disk directory name, not the
        # frontmatter `name:` — the two are the same in practice (the
        # directory name is the fallback), but only one of them is
        # guaranteed to be a safe single path segment.
        path = harness_pointer_path(harness, tier_root, tier, agent_name)

        if harness == "claude-code":
            outcome = _write_pointer_file(path, _render_claude_code(agent, _agent_md_path(tier_root, agent), tier))
        elif harness == "cline":
            outcome = _write_pointer_file(path, _render_cline(agent, _agent_md_path(tier_root, agent), tier))
        else:
            installed = catalog.list_agents(tier_root)
            outcome = _write_managed_block(path, _render_context_block(installed, tier_root, tier))

        results.append({"harness": harness, "path": path, **outcome})

    return results
