"""Update, diff, and remove an already-installed agent.

``install.copy_agent``'s contract is deliberately narrow: copy when absent,
leave alone when present (see ``install.py``'s own docstring). That
narrowness is correct for install itself, but it means nothing in this repo
can answer "has this copy drifted from its source", "bring it up to date",
or "take it back out" once an agent has been installed once. This module
adds those three operations — issue #5's "agent lifecycle across tiers" —
kept out of ``install.py`` on purpose, so the never-overwrite guarantee
``copy_agent`` gives stays exactly what it is: reaching for update, diff, or
remove here is always something a person did on purpose, never a side
effect install could trigger on its own.

Every operation takes the same ``(name, src_root, dst_root)`` shape
``install.copy_agent`` does, or the ``(name, tier_root)`` shape
``install.generate_harness_adapters`` does, and none of them re-derive
tier resolution, pointer rendering, or the hand-authored-file rule: update
and diff call ``install.copy_agent``, and remove calls
``install.remove_harness_adapters``, so the one place that knows what
"generated by ai-agents" means stays ``install.py``.
"""

from __future__ import annotations

import shutil
from pathlib import Path

from . import install

__all__ = ["diff_agent", "update_agent", "remove_agent", "LocalDivergenceError"]


class LocalDivergenceError(RuntimeError):
    """Raised by ``update_agent`` when the installed copy has diverged and
    no force was given.

    Carries the same diff dict ``diff_agent`` would have returned as
    ``.diff``, and the agent name as ``.name``, so a caller that catches
    this does not need to call ``diff_agent`` a second time to find out
    what would have changed.
    """

    def __init__(self, name: str, diff: dict):
        self.name = name
        self.diff = diff
        total = len(diff["changed"]) + len(diff["local_only"]) + len(diff["master_only"])
        super().__init__(
            f"{name!r} has diverged from its source ({total} file(s) differ); "
            "pass force=True (CLI: --force) to overwrite the local copy"
        )


def _relative_files(root: Path) -> set[str]:
    """Every regular file under ``root``, as POSIX paths relative to it.

    Directories are not compared on their own — an empty directory carries
    no content, so two agent trees differing only by an empty directory
    (e.g. an unused ``Skills/``) are not "diverged" under the definition
    ``diff_agent`` uses.
    """
    return {p.relative_to(root).as_posix() for p in root.rglob("*") if p.is_file()}


def diff_agent(name: str, src_root: Path, dst_root: Path) -> dict:
    """Compare an installed agent against its counterpart at a higher tier.

    **Definition of "diverged"**: every regular file under
    ``src_root/agents/<name>`` and ``dst_root/agents/<name>`` is read and
    compared byte-for-byte, keyed by its path relative to the agent
    directory. A file only one side has, or a file both sides have with
    different bytes, both count as divergence — mtimes and permissions are
    never consulted, since neither is meaningful for markdown that may have
    been edited with any tool, on any OS, at any time.

    This is deliberately the strict, symmetric definition: ``install.py``'s
    own docstring already treats a present destination as "may have been
    edited on purpose", so *any* difference in either direction counts as
    evidence of that — not only a changed file, but also a file added
    locally that the master doesn't have, or a file the master has grown
    since install that the local copy is simply missing. The alternative
    (only flag files common to both sides whose content differs) would let
    ``update_agent`` silently delete a locally-added file or silently
    reintroduce a locally-deleted one without ever tripping the guard, and
    both of those are exactly the kind of local edit the never-overwrite
    default exists to protect.

    Returns ``{"diverged": bool, "master_only": [...], "local_only": [...],
    "changed": [...]}``. Each list is sorted and holds paths relative to the
    agent directory. ``master_only`` exists upstream but is missing locally
    (an update would add these); ``local_only`` exists locally but is
    missing upstream (an update — which recopies from source — would
    delete these); ``changed`` exists on both sides with different bytes.

    Raises ``FileNotFoundError`` if the agent is missing from either root.
    Purely reads: no directory is created, no file is written or touched,
    so this is safe to call as often as wanted, including from a `diff`
    CLI command that must never mutate anything.
    """
    src = Path(src_root) / "agents" / name
    dst = Path(dst_root) / "agents" / name

    if not src.is_dir():
        raise FileNotFoundError(f"agent {name!r} not found in {src_root}")
    if not dst.is_dir():
        raise FileNotFoundError(f"agent {name!r} is not installed at {dst_root}")

    src_files = _relative_files(src)
    dst_files = _relative_files(dst)
    common = src_files & dst_files

    master_only = sorted(src_files - dst_files)
    local_only = sorted(dst_files - src_files)
    changed = sorted(rel for rel in common if (src / rel).read_bytes() != (dst / rel).read_bytes())

    return {
        "diverged": bool(master_only or local_only or changed),
        "master_only": master_only,
        "local_only": local_only,
        "changed": changed,
    }


def update_agent(name: str, src_root: Path, dst_root: Path, *, force: bool = False) -> dict:
    """Refresh an installed agent from a higher tier.

    A refresh is delete-then-copy, not a merge — there is no per-file
    reconciliation, mirroring ``install.copy_agent``'s own all-or-nothing
    shape. This is exactly the refresh path ``install.py``'s docstring
    already promises ("refreshing it means removing it first"), made
    explicit and guarded: the deletion only runs after ``diff_agent``
    confirms nothing would be silently lost, or after the caller has said
    ``force=True`` and accepted that it would be.

    Returns the ``diff_agent`` result that was checked, whether or not
    anything had actually diverged, so a caller always learns what changed
    even on a clean update.

    Raises ``FileNotFoundError`` if the agent is not already installed at
    ``dst_root`` (this is a refresh operation, not a first install — see
    ``install.copy_agent``) or if it is missing from ``src_root``. Raises
    ``LocalDivergenceError`` if diverged and ``force`` is not set. Neither
    error leaves any file touched — the divergence check runs entirely
    before the destination directory is removed.
    """
    dst = Path(dst_root) / "agents" / name
    if not dst.is_dir():
        raise FileNotFoundError(f"agent {name!r} is not installed at {dst_root}; use install first")

    diff = diff_agent(name, src_root, dst_root)
    if diff["diverged"] and not force:
        raise LocalDivergenceError(name, diff)

    shutil.rmtree(dst)
    install.copy_agent(name, src_root, dst_root)
    return diff


def remove_agent(name: str, tier_root: Path, *, tier: str | None = None) -> dict:
    """Delete an installed agent and the pointer files generated for it.

    Pointer cleanup is delegated to ``install.remove_harness_adapters`` —
    the module that owns the hand-authored-file distinction and the
    context-block rendering — and runs before the agent directory itself
    is removed. That ordering is not load-bearing (see
    ``remove_harness_adapters``'s own docstring: it excludes ``name`` from
    the "agents remaining" list itself), it is chosen only so a failure
    partway through cleanup leaves the agent directory in place rather than
    gone with dangling pointers behind.

    Returns ``{"removed_agent": bool, "pointers": [...]}`` where
    ``"pointers"`` is ``remove_harness_adapters``'s own per-harness result
    list — see its docstring for the shape of each entry.

    Raises ``FileNotFoundError`` if the agent is not installed at
    ``tier_root``.
    """
    tier_root = Path(tier_root)
    agent_dir = tier_root / "agents" / name
    if not agent_dir.is_dir():
        raise FileNotFoundError(f"agent {name!r} is not installed at {tier_root}")

    pointers = install.remove_harness_adapters(name, tier_root, tier=tier)
    shutil.rmtree(agent_dir)

    return {"removed_agent": True, "pointers": pointers}
